FROM python:3.10

WORKDIR /fastapi_week3

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "fastapi_week3:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
